name: Update GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch GitHub Stats with Private PRs
        run: |
          mkdir -p assets
          curl -v "https://github-readme-stats.vercel.app/api?username=MabelSamuel&count_private=true&show_icons=true&theme=dark&hide_border=true&token=${{ secrets.GH_STATS_TOKEN }}" -o assets/github-stats.svg

      - name: Debug image output
        run: ls -lh assets && file assets/github-stats.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add assets/github-stats.svg
          git commit -m "chore: update GitHub stats" || echo "No changes to commit"
          git push
